
#@gcc -m32 visa_simple_test.c -o visa_simple_test -L/usr/lib/gcc/i586-linux-gnu/5/ -L/usr/local/lib/ -L/usr/local/lib/LabVIEW-2014/patchlib/ -L/usr/lib/i386-linux-gnu/ -lvisa -lnipalu

all:
	@gcc visa_simple_test.c -o visa_simple_test -L/usr/lib/gcc/i586-linux-gnu/5/ -L/usr/local/lib64/ -L/usr/local/lib/LabVIEW-2014/patchlib/ -L/usr/lib/i386-linux-gnu/ -lvisa -lnipalu
